#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Symbol.XamarinEMDK.BarcodeSample1.Resource", IsApplication=true)]

namespace Symbol.XamarinEMDK.BarcodeSample1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int triggers_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int buttonStartScan = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int buttonStopScan = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int checkBoxCode128 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int checkBoxCode39 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int checkBoxContinuous = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int checkBoxEAN13 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int checkBoxEAN8 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int relativeLayout1 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int scrollView1 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int spinnerScanners = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int spinnerTriggers = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int textView16 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int textView26 = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int textView6 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int textViewData = 2130968590;
			
			// aapt resource value: 0x7F040010
			public const int textViewlblScanner = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int textViewlblTrigger = 2130968593;
			
			// aapt resource value: 0x7F04000F
			public const int textViewStatus = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int Landscape = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Portrait = 2131034113;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int scanner_prompt = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int trigger_prompt = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
